# California Housing Regression MLP

We will use Scikit-Learn’s fetch_california_housing to get the dataset. This is a simple dataset with no missing values

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

In [2]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
housing = fetch_california_housing()

X_train_full, X_test, y_train_full, y_test = train_test_split(
    housing.data, housing.target)

X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_full, y_train_full)

In [4]:
X_train_full

array([[   4.9688    ,   35.        ,    5.38059701, ...,    2.96641791,
          34.25      , -118.48      ],
       [   1.        ,   52.        ,    3.92708333, ...,    5.52083333,
          36.75      , -119.79      ],
       [   6.5615    ,    8.        ,    6.27048586, ...,    3.63959391,
          37.57      , -122.07      ],
       ...,
       [   7.3445    ,   13.        ,    7.89772727, ...,    3.22727273,
          37.89      , -121.93      ],
       [   1.6384    ,   42.        ,    3.76738609, ...,    3.91127098,
          33.79      , -118.18      ],
       [   3.6591    ,   52.        ,    4.93190661, ...,    2.12840467,
          37.84      , -122.25      ]])

Regression tasks need a scaled parameters

In [5]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)
X_test_scaled = scaler.transform(X_test)

## Model Creation

In case of regression, the output layer has a single neuron (since we only want to
predict a single value) and uses no activation function. The loss function is the
mean squared error. Since the dataset is quite noisy, we just use a single hidden layer
with fewer neurons than before, to avoid overfitting.

In [6]:
model = keras.models.Sequential([
    keras.layers.Dense(30, activation="relu", input_shape=X_train.shape[1:]),
    keras.layers.Dense(1)
])

2022-09-25 11:43:29.426544: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-25 11:43:29.429549: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


## Model Compiling

In [7]:
model.compile(loss="mean_squared_error", optimizer="sgd")

## Model Training

In [8]:
history = model.fit(X_train, y_train, epochs=20, validation_data=(X_valid, y_valid))

Epoch 1/20
363/363 [==============================] - 3s 7ms/step - loss: 2248883005288941008843702272.0000 - val_loss: 156771481705231941632.0000
Epoch 2/20
363/363 [==============================] - 3s 8ms/step - loss: 10911630359862968320.0000 - val_loss: 66895717859328.0000
Epoch 3/20
363/363 [==============================] - 2s 5ms/step - loss: 4656079044608.0000 - val_loss: 28545364.0000
Epoch 4/20
363/363 [==============================] - 2s 7ms/step - loss: 1986791.7500 - val_loss: 13.7270
Epoch 5/20
363/363 [==============================] - 3s 8ms/step - loss: 2.2081 - val_loss: 1.2867
Epoch 6/20
363/363 [==============================] - 4s 10ms/step - loss: 1.3428 - val_loss: 1.2902
Epoch 7/20
363/363 [==============================] - 2s 6ms/step - loss: 1.3429 - val_loss: 1.2871
Epoch 8/20
363/363 [==============================] - 4s 10ms/step - loss: 1.3423 - val_loss: 1.2903
Epoch 9/20
363/363 [==============================] - 3s 8ms/step - loss: 1.3431 - val_loss: 

## Evaluation and Testing

In [9]:
mse_test = model.evaluate(X_test, y_test)
X_new = X_test[:3] # pretend these are new instances
y_pred = model.predict(X_new)

162/162 [==============================] - 1s 5ms/step - loss: 1.3400


In [10]:
y_pred

array([[2.088968],
       [2.088968],
       [2.088968]], dtype=float32)

In [11]:
y_test[:3]

array([5.00001, 1.508  , 5.00001])

As you can see the model prediction is not near to the actuals. This means a lot of tuning is needed